Fix a lot of ssl.SSLEOFError exceptions due to client hanging up
This seems to have been the cause of **many** RemoteStash pull failures!

What was happening here:

  - Client would call `GET /pull` when server has a binary file in stash
  - The client would see HTTP/1.1 200 ...long potentially binary string here...
  - Client would fail to parse the HTTP status line, and rightfully hang up
  - Server would see EOF in the middle of sending the item content
  - Exception would be thrown, and second 500 error response would trigger!
  - Client never sees the second 500 error response... but at least it was logged!

Error was:

    ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2426)

Traceback (most recent call last):
  File "/home/exampleuser/.local/bin/remotestash", line 919, in do_GET
    getattr(self, method)()
  File "/home/exampleuser/.local/bin/remotestash", line 879, in last
    self.respond_item( item )
  File "/home/exampleuser/.local/bin/remotestash", line 1092, in respond_item
    self.respond( 200, headers, message, log_message=f'Request: {item}' )
  File "/home/exampleuser/.local/bin/remotestash", line 1189, in respond
    self.end_headers()
  File "/home/exampleuser/.pyenv/versions/3.10.12/lib/python3.10/http/server.py", line 535, in end_headers
    self.flush_headers()
  File "/home/exampleuser/.pyenv/versions/3.10.12/lib/python3.10/http/server.py", line 539, in flush_headers
    self.wfile.write(b"".join(self._headers_buffer))
  File "/home/exampleuser/.pyenv/versions/3.10.12/lib/python3.10/socketserver.py", line 826, in write
    self._sock.sendall(b)
  File "/home/exampleuser/.pyenv/versions/3.10.12/lib/python3.10/ssl.py", line 1237, in sendall
    v = self.send(byte_view[count:])
  File "/home/exampleuser/.pyenv/versions/3.10.12/lib/python3.10/ssl.py", line 1206, in send
    return self._sslobj.write(data)
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:2426)